version: 2.1

orbs:
  java-build: My-Demo-Orb/java-build@1.0
  
jobs:
  build:
    executor: java-executor
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - java-build/build
    
workflows:
  version: 2
  build-deploy:
    jobs:
      - build

