version: 2
jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - java-build/build:
          version: 2.1
    environment:
      JVM_OPTS: -Xmx3200m
workflows:
  version: 2
  build:
    jobs:
      - build

